name: build-push

on:
  push:
    branches:
      - 'main'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
  
      - name: Set up Docker Build
        uses: docker/setup-buildx-action@v1
        
      - name: Configure Docker
        uses: docker/login-action@v1
        with:
          registry: ${{ secrets.REGISTRY_URL }}
          username: ${{ secrets.REGISTRY_USERNAME  }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
      
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        env:
          VUE_APP_GRAPHQL_URI: ${{ secrets.VUE_APP_GRAPHQL_URI }}
        run: echo "${VUE_APP_GRAPHQL_URI}"
        with:
          push: true
          VUE_APP_GRAPHQL_URI: ${{ secrets.VUE_APP_GRAPHQL_URI }}
          tags: ${{ secrets.IMAGE_NAME }}:${{ secrets.IMAGE_TAG }}


      - name: Deploy Caprover
        uses: floms/action-caprover@v1
        with:
            host: '${{ secrets.CAPROVER_HOST }}'
            password: '${{ secrets.CAPROVER_PASSWORD }}'
            app: '${{ secrets.CAPROVER_APP_NAME }}'
            image: ${{ secrets.IMAGE_NAME }}:${{ secrets.IMAGE_TAG }}